
# html lang
language: zh-CN

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
-

# scripts loaded in the end of the body
scripts:
- /scripts/index.js